server:
  port: 8282
#default api-doc is
#http://localhost:8080/v3/api-docs/
#changed to http://localhost:8080/api-docs/
springdoc:
  api-docs:
    path: /api-docs

spring:
  datasource:
        url: jdbc:h2:mem:testdb
        driverClassName: org.h2.Driver
        username: sa
        password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
      settings.web-allow-others: false
logging:
  level:
    root: INFO
